### ISSUE TITLE
Codes 1.5.0

### ISSUE THREAD

**Issue by kyrasantae** [Razer2015/NordeaRootBypasser#4]
Doesn't work anymore with latest codes app. Just shows screen saying root was detected.

**Comment by Enskan** [comment]
Hey,

Same thing here, since about 14th of june Nordea codes recognises root. I had been using the similar module " XposedCodeApp". I the process i also tried this module which does not work either. 

Nordeas FAQ says that "the new version of the code app reconises root better than the previous"

Please help us soon :)

**Comment by Razer2015** [comment]
@kyrasantae 
@Enskan 

I think I might have found the new root detection but I can't test it thoroughly since I only have access to rooted VM android (not a real device).

There was apparently a hook detection as well as root detection :D I first bypassed the root detection and it seemed to work but then crashed. I guess I got that fixed but not entirely sure. I've committed the changes to repository and compiled a new version, please give me a feedback on how it works.

Download: https://github.com/Razer2015/NordeaRootBypasser/releases/tag/v1.1

**Comment by kyrasantae** [comment]
Not working yet.

**Comment by Razer2015** [comment]
@kyrasantae 

What is the problem? It still says root detected or is it crashing or something?

My virtual android device works great so I don't know what could be the problem and so I can't even debug it further :(. 

Or do you maybe have another version of the APK since they do say that it can vary depending on device? I've tested it on this APK (if you could check the MD5 or SHA1 from yours?): 
![image](https://user-images.githubusercontent.com/10619845/27256447-84f63816-53bd-11e7-87b2-6a0cd45d672c.png)

MD5: 30169142EA1D8E3FFFBFDCFD434E6FD5
SHA1: FE79C2DECA0132946A34CE63AB54ACC23F0FCCF8

And possibly a logcat from the point where you open the Nordea Codes app?

**Comment by villelappi** [comment]
Hi,

I tested latest version 1.1 and it works. Thanks!

**Comment by Razer2015** [comment]
@villelappi Cool, thanks for feedback.

**Comment by kyrasantae** [comment]
I still get the root detected screen. The hashes for my package are the same as yours. I'll try to upload some logcat material tonight, but in the meantime I can tell you that my device is using Android 4.4.2.

**Comment by Razer2015** [comment]
@kyrasantae 

Have you double checked that the installed version of my module is 1.1 and that you have it activated + rebooted your device after that?

Also, take the logcat from the first startup of the app after reboot. I don't know if it's just a bug in the virtual android or not but it doesn't log everything if I take the logcat from the second startup IF I haven't force closed the nordea codes app before.

**Comment by kyrasantae** [comment]
Yes, it shows that I have 1.1. I have switched the module off and on and rebooted the device multiple times over the weekend, with the same result.

**Comment by Razer2015** [comment]
That's weird that it works for some and not for you :/ Well, lets hope the logcat can shed some light on this issue.

**Comment by Enskan** [comment]
I'm using a Meizu pro 5 phone and it seems to be working! I can start the code app but not use the actual codes until a get a new account again (reinstalled the code app in the troubleshooting process). I am using Xposed framework version 87. 

Thank you very much Razer2015!

**Comment by kyrasantae** [comment]
Hey, I got it working again. First I tried disabling the module, rebooting, then enabling it, and rebooting again. At this point, instead of going to the root detected error, it popped the error that the version of the codes app was no longer in use. 

Enskan's post gave me the idea to try reinstalling.
So I deleted the device from my netbank, reinstalled the code app, and then added it again in netbank. Now it works :) Thanks to both of you!

**Comment by kyrasantae** [comment]
Update to 1.5.1 has broken it again. Same root detected screen. Anyone else?

**Comment by Razer2015** [comment]
@kyrasantae Added support for 1.5.1 in the newest release.

**Comment by kyrasantae** [comment]
Working again. Thanks!
